import type { Metadata } from "next";
import { notFound } from "next/navigation";
import { STRAPI_URL as cmsUrl } from "@/lib/strapi";
type SitePage={documentId?:string;title:string;slug:string;heroEyebrow?:string;heroTitle?:string;heroAccent?:string;heroDescription?:string;heroImage?:{url?:string};sections?:Array<{eyebrow?:string;heading?:string;body?:string;linkLabel?:string;linkUrl?:string}>;seoTitle?:string;seoDescription?:string;canonicalUrl?:string;noIndex?:boolean};
const siteUrl=process.env.NEXT_PUBLIC_SITE_URL??"https://kitchen-master-two.vercel.app";
const FALLBACK_PAGES:Record<string,SitePage>={
  "private-dining":{title:"Private Dining",slug:"private-dining",heroEyebrow:"Private dining",heroTitle:"Gather around",heroAccent:"our table.",heroDescription:"Plan a private dinner, celebration, or group dining experience with Kitchen Master.",sections:[{eyebrow:"Start planning",heading:"Make it memorable.",body:"Tell our team about your date, party size, preferred location, and the kind of occasion you’re planning.",linkLabel:"Email our events team",linkUrl:"mailto:Management@kitchenmasterga.com"}]},
  contact:{title:"Contact",slug:"contact",heroTitle:"Come say",heroAccent:"hello.",heroDescription:"Questions, feedback, and general inquiries for Kitchen Master."},
  franchise:{title:"Franchise Opportunities",slug:"franchise",heroTitle:"Grow with",heroAccent:"Kitchen Master.",heroDescription:"Learn about future franchise and development opportunities."},
};
async function getPage(slug:string,preview=false):Promise<SitePage|null>{const fallback=FALLBACK_PAGES[slug]??null;if(!cmsUrl)return fallback;try{const secret=process.env.STRAPI_PREVIEW_SECRET;const query=preview&&secret?`?preview=1&previewSecret=${encodeURIComponent(secret)}`:"";const response=await fetch(`${cmsUrl.replace(/\/$/,"")}/api/kitchen-master-content${query}`,preview?{cache:"no-store"}:{next:{revalidate:60}});if(!response.ok)return fallback;const payload=await response.json();return payload.pages?.find((page:SitePage)=>page.slug===slug||page.documentId===slug)??fallback;}catch{return fallback;}}
function imageUrl(page:SitePage){const url=page.heroImage?.url;if(!url)return null;return url.startsWith("/")?`${cmsUrl?.replace(/\/$/,"")}${url}`:url;}
export async function generateMetadata({params,searchParams}:{params:Promise<{slug:string}>;searchParams:Promise<{preview?:string}>}):Promise<Metadata>{const {slug}=await params;const query=await searchParams;const preview=query.preview==="1";const page=await getPage(slug,preview);if(!page)return {};return {title:{absolute:page.seoTitle||page.title},description:page.seoDescription||page.heroDescription,alternates:{canonical:page.canonicalUrl||`${siteUrl}/pages/${page.slug}`},robots:preview||page.noIndex?{index:false,follow:false}:undefined};}
export default async function CmsPage({params,searchParams}:{params:Promise<{slug:string}>;searchParams:Promise<{preview?:string}>}){const {slug}=await params;const query=await searchParams;const page=await getPage(slug,query.preview==="1");if(!page)notFound();const background=imageUrl(page);return <main className="cms-page" style={background?{backgroundImage:`linear-gradient(90deg,#11100ff2,#11100f88),url(${background})`}:undefined}><header><a className="gateway-brand" href="/"><span className="brand-mark">KM</span><span>KITCHEN MASTER</span></a><a className="text-link" href="/">Back to restaurants →</a></header><section className="cms-page-hero"><p className="kicker">{page.heroEyebrow||page.title}</p><h1>{page.heroTitle||page.title}<br/><em>{page.heroAccent}</em></h1>{page.heroDescription&&<p>{page.heroDescription}</p>}</section>{Array.isArray(page.sections)&&page.sections.map((section,index)=><section className="cms-content-block" key={index}>{section.eyebrow&&<small>{section.eyebrow}</small>}{section.heading&&<h2>{section.heading}</h2>}{section.body&&<p>{section.body}</p>}{section.linkUrl&&<a className="button button-red" href={section.linkUrl}>{section.linkLabel||"Learn more"} →</a>}</section>)}</main>}
